### ISSUE TITLE
Potential dereference of null pointer

### ISSUE THREAD

**Issue by technic** [antony-jr/AppImageUpdaterBridge#13]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Potential dereference of nullptr.
Please see clang [report](https://technic93.gitlab.io/-/e2designer/-/jobs/138543310/artifacts/build/report/2018-12-24-225705-25-1/report-92fee4.html#EndPath) in my gitlab-ci (link may expire)
That's why I don't like macros, because it makes things hard to read

**Ways to Reproduce the issue (optional):**

**Comment by antony-jr** [comment]
@technic Then I think we should create a private structure to do this with RAII. I guess this is for the code readability.

**Comment by technic** [comment]
Do you need that trylock all the time? if it failed to lock, the corresponding value would not be set. This is not what I expect as a user of the library.

**Comment by antony-jr** [comment]
Well this class is not currently documented , i.e its not ready for use , I'm planning to entirely avoid mutex and use signals and slots which should make this non-blocking and also make it thread safe. If we use QMutexLocker , it will block threads if the mutex is locked which is not intended that's why I temporarily used tryLock(). We just need to ship this class to opaque pointer and use signals to call the set methods in order to make it thread safe. (But we can't use multiple threads since GUI has to run in the main thread.)

**Comment by antony-jr** [comment]
could you confirm this now ?

**Comment by technic** [comment]
Ok, I pulled your update to my git submodule and I don't see any complains from clang now.
